# Site wide configuration

title: musician's musings
locale: en_US
timezone: EST
description: where kevi occasionally publishes thoughts
logo: profile.png
search: true
url: #your-site-url
external_data_url: # common url for images and other external data

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

paginate: 20
paginate_path: /posts/page:num


# Site owner
owner:
  name: kevi
  avatar: profile.png
  email: #youremail
  disqus-shortname: #your-disqus-shortname
  twitter: #your-twitter-name
  facebook: kevi8991
  github: #your-github-name
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram:
    user: kevi8991
    userId: 1823322499
    clientId: #instagram-clientId
  flickr: #username
  tumblr: #tumblr-name
  pinterest: #username
  weibo: #userid
  soundcloud: #soundcloud-name
  mixcloud: #mixcloud-name
  lastfm: #username
  tawkto:
    siteID: #tawkto-siteID
  google:
    plus:
    analytics: #google-analytics-id
    verify:
    ad-client:
    ad-slot:
  bing-verify:
